version: '2'
services:
    db:
        image: mysql
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: typo3
          MYSQL_DATABASE: typo3
          MYSQL_USER: typo3
          MYSQL_PASSWORD: typo3
        volumes_from:
          - apache
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --sql-mode=""
    apache:
        build: apache
        ports:
            - 80:80
        volumes:
            - ./logs/apache/:/var/log/apache2
            - ../src:/var/www/
        tty: true
